version: "3.7"
services:
  turnierverwaltung:
    build: ./Turnierverwaltung
    container_name: turnierverwaltung
    environment:
      BASE_URL_TURNIER: 'http://localhost:3007/'
    ports:
      - "3007:3007"
