version: "3.7"
services:
  appgateway:
    build: ./AppGateway
    container_name: appgateway
    environment:
      BASE_URL_APPGATEWAY: 'http://localhost:3000/'
    ports:
      - "3000:3000"
  zugriffsverwaltung:
    build: ./Zugriffsverwaltung
    container_name: zugriffsverwaltung
    environment:
      BASE_URL_ZUGRIFF: 'http://localhost:3005/'
    ports:
      - "3005:3005"
  personenverwaltung:
    build: ./Personenverwaltung
    container_name: personenverwaltung
    environment:
      BASE_URL_PERSONEN: 'http://localhost:3004/'
    ports:
      - "3004:3004"
  turnierverwaltung:
    build: ./Turnierverwaltung
    container_name: turnierverwaltung
    environment:
      BASE_URL_TURNIER: 'http://localhost:3007/'
    ports:
      - "3007:3007"
  mannschaftsverwaltung:
    build: ./Mannschaftsverwaltung
    container_name: mannschaftsverwaltung
    environment:
      BASE_URL_MANNSCHAFT: 'http://localhost:3006/'
    ports:
      - "3006:3006"
