version: "3.7"
services:
  zugriffsverwaltung:
    build: ./Zugriffsverwaltung
    container_name: zugriffsverwaltung
    environment:
      BASE_URL_TURNIER: 'http://localhost:3005/'
    ports:
      - "3005:3005"
  turnierverwaltung:
    build: ./Turnierverwaltung
    container_name: turnierverwaltung
    environment:
      BASE_URL_TURNIER: 'http://localhost:3007/'
    ports:
      - "3007:3007"
  mannschaftsverwaltung:
    build: ./Mannschaftsverwaltung
    container_name: mannschaftsverwaltung
    environment:
      BASE_URL_MANNSCHAFT: 'http://localhost:3006/'
    ports:
      - "3006:3006"
