
GET http://google.com HTTP/1.1

###
POST http://localhost:3007/createTurnier
content-type: application/json

{
    "name": "testTurnier"
}
###

POST http://localhost:3007/addTeilnehmerToTurnier
content-type: application/json

{
    "turnierID": 1,
    "teilnehmerIDs": [16]
}

###

POST http://localhost:3007/addSpielToTurnier
content-type: application/json

{
    "turnierID": 1,
    "game": {
        "team1Id": 16,
        "team2Id": 17,
        "team1Punkte": 1,
        "team2Punkte": 2
    }
}
###
DELETE http://localhost:3007/removeSpielFromTurnier/11

###
DELETE http://localhost:3007/removeTeilnehmerFromTurnier/
content-type: application/json

{
    "turnierID": 1,
    "teilnehmerIDs": [17]
}
###
GET http://localhost:3007/getTurniere

###

DELETE  http://localhost:3007/deleteTurnier/3
