
GET http://google.com HTTP/1.1

###
POST http://localhost:3007/createTurnier
content-type: application/json

{
    "name": "testTurnier"
}
###

POST http://localhost:3007/addTeilnehmerToTurnier
content-type: application/json

{
    "turnierID": 7,
    "teilnehmerIDs": [7, 8, 9]
}

###

POST http://localhost:3007/addSpielToTurnier
content-type: application/json

{
    "turnierID": 4,
    "game": {
        "team1Id": 8,
        "team2Id": 9,
        "team1Punkte": 0,
        "team2Punkte": 2
    }
}
###
DELETE http://localhost:3007/removeSpielFromTurnier/14

###
DELETE http://localhost:3007/removeTeilnehmerFromTurnier/4/7
###
GET http://localhost:3007/getTurniere

###

DELETE  http://localhost:3007/deleteTurnier/3
