
GET http://google.com HTTP/1.1

###
POST http://localhost:3004/persons
content-type: application/json

{
    "firstName": "testName", 
    "lastName": "testLastname", 
    "birthday": 1611586940792
}

### Fussballspieler

POST http://localhost:3004/persons
content-type: application/json

{
    "type": "fussballspieler",
    "firstName": "testName", 
    "lastName": "testLastname", 
    "birthday": 1611586940792,
    "fieldPosition": "center"
}

### Handballspieler

POST http://localhost:3004/persons
content-type: application/json

{
    "type": "handballspieler",
    "firstName": "testName", 
    "lastName": "testLastname", 
    "birthday": 1611586940792,
    "fieldPosition": "center"
}

### Tennisspieler

POST http://localhost:3004/api/v1/personenverwaltung/persons
content-type: application/json

{
    "type": "tennisspieler",
    "firstName": "testName", 
    "lastName": "testLastname", 
    "birthday": 1611586940792,
    "handedness": "left"
}

### Trainer

POST http://localhost:3004/persons
content-type: application/json

{
    "type": "trainer",
    "firstName": "testName", 
    "lastName": "testLastname", 
    "birthday": 1611586940792,
    "experience": 17
}

### Physiotherapeut

POST http://localhost:3004/api/v1/personenverwaltung/persons
content-type: application/json

{
    "type": "physiotherapeut",
    "firstName": "testName",
    "lastName": "testLastname",
    "birthday": 1611586940792,
    "treatmentType": "Kinesio Taping"
}

###

GET http://localhost:3004/api/v1/personenverwaltung/persons

###

GET http://localhost:3004/persons/2

###

DELETE  http://localhost:3004/person/5

###

PUT  http://localhost:3004/api/v1/personenverwaltung/persons/1
content-type: application/json

{
    "type": "fussballspieler",
    "firstName": "asdasd",
    "lastName": "fgg",
    "birthday": 1611586940792,
    "fussballspieler": {
      "id": 1,
      "fieldPosition": "af"
    }
  }