# den accesstoken austesten (hier die Antwort vom login request einfügen)
GET http://localhost:3004/getCurrentUser HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6MSwiaWF0IjoxNjExNjUxODM2LCJleHAiOjE2MTE2NTI3MzZ9.9sjkvH0tAli1PQxphowvK_Fo4deQF6kofwmLaaCMukw

###

# einen Access- und Refreshtoken von der Zugriffsverwaltung holen
POST http://localhost:3005/login HTTP/1.1
content-type: application/json

{
    "login": "admin",
    "password": "admin"
}

###

# einen neuen Accesstoken anfordern
POST http://localhost:3005/token HTTP/1.1
