# den accesstoken austesten (hier die Antwort vom login request einfügen)
GET http://localhost:3005/getCurrentUser HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6MSwiaWF0IjoxNjExNjUzNDQwLCJleHAiOjE2MTE2NTQzNDB9.OGdAiE_BVn3N7deaf5HLyjItD43PQeomm-sLobjo0vE

###

# einen Access- und Refreshtoken von der Zugriffsverwaltung holen
POST http://localhost:3005/api/zugriffsverwaltung/login HTTP/1.1
content-type: application/json

{
    "login": "admin",
    "password": "admin"
}

###

# einen neuen Accesstoken anfordern
POST http://localhost:3005/api/zugriffsverwaltung/token HTTP/1.1
