GET http://google.com HTTP/1.1

###
POST http://localhost:3006/createMannschaft
content-type: application/json

{
    "name": "Arsenal22323", 
    "sportType": "Fussball", 
    "mitglieder": [2,3]
}
###

GET http://localhost:3006/getMannschaften

###
GET http://localhost:3006/getMannschaft/1

###
DELETE http://localhost:3006/deleteMannschaft/1

###
PUT http://localhost:3006/addToMannschaft
content-type: application/json

{
    "personenIDs": [6, 7, 8],
    "mannschaftID": 16
}

###

PUT http://localhost:3006/removeFromMannschaft
content-type: application/json

{
    "personenID": 7,
    "mannschaftID": 16
}

###
POST http://localhost:3006/deleteFromMann
content-Type: application/json

{
    "personenIDs": [6, 7, 8],
    "mannschaftID": 1
}