GET http://localhost:3005/getData HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6MSwiaWF0IjoxNjExNTgyMzQ4LCJleHAiOjE2MTE1ODMyNDh9.52Xd4nJO7hLoZfa-YwuB5UYKDHcDrtZRBfRYVBjxmII

###

POST http://localhost:3005/login HTTP/1.1
content-type: application/json

{
    "login": "admin",
    "password": "admin"
}

###

GET http://google.com HTTP/1.1

###

POST http://localhost:3005/user
content-type: application/json

{
    "login": "user7", 
    "password": "user", 
    "role": 0
}
###


###

GET http://localhost:3005/token HTTP/1.1

###

GET http://172.25.108.80:3005/getData HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbWVzIiwicm9sZSI6Im1lbWJlciIsImlhdCI6MTYwODE5ODIzOSwiZXhwIjoxNjA4MTk5MTM5fQ.CVW9kZlZ81X_ZkRzfl5Dm4C3PY60C25vRnHSIMoAjaM
###

POST http://172.25.108.80:3005/token HTTP/1.1

###

POST http://172.25.108.80:3005/login HTTP/1.1
content-type: application/json

{
    "username": "james",
    "password": "pw123"
}

###


