openapi: '3.0.2'
info:
  version: 1.0.0
  title: Personenverwaltung
  description: Beschreibung der API-Schnittstellen für die Personenverwaltung
  contact:
   name: Florian, Jonas, Lars
servers:
  - url: http://localhost:3004

paths:
  /api/v1/personenverwaltung/persons:
    get:
      description: Returns a JSON array of person objects.
      responses:
        '200':    # status code
          description: A JSON array of persons
          content:
            application/json:
              schema: 
                type: array
components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: integer
          format: int64
        classification:
          type: string
        firstname:
          type: string
        lastname:
          type: string
      required:
        - id